### ISSUE TITLE
Release recent changes

### ISSUE THREAD

**Issue by n1ngu** [gcoop-libre/tryton-filestore-s3#3]
While the latest patches can be installed right from this github repository, a release in pypi would come in handy.

I guess the release process is not automated in any way so I fear there is little the community can help here.

Is the former pypi project publisher account operative? It's been a while since the last activity! https://pypi.org/user/lukio/ @lukio I guess that's you.

**Comment by lukio** [comment]
HI @n1ngu a new release at pypi was uploaded.

https://pypi.org/project/tryton-filestore-s3/0.2.0/

Thanks!
